blank_issues_enabled: true
contact_links:
  - name: KOOK 频道
    url: https://kook.top/Kx7n3t
    about: Hello Minecraft! Launcher 的官方 KOOK 频道。
  - name: Discord 频道
    url: https://discord.gg/jVvC7HfM6U
    about: Hello Minecraft! Launcher 的官方 Discord 频道。
  - name: 赞助通道
    url: https://afdian.net/@huanghongxun
    about: 前往爱发电赞助 HMCL。赞助后可以申请加入官方 QQ 群反馈问题。
  - name: 其他反馈
    url: https://github.com/huanghongxun/HMCL/discussions/new/choose
    about: 通过 Discussions 反馈其他问题。
