blank_issues_enabled: true
contact_links:
  - name: QQ 群 | QQ Group
    url: https://docs.hmcl.net/groups.html
    about: Hello Minecraft! Launcher 的官方 QQ 交流群。
  - name: Discord 服务器 | Discord Server
    url: https://discord.gg/jVvC7HfM6U
    about: Hello Minecraft! Launcher 的官方 Discord 服务器。
