name: Debug Label Event
on:
  pull_request:
    types: [labeled]
  pull_request_target :
      types: [ labeled ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Label added: ${{ github.event.label.name }}"
          echo "Action: ${{ github.event.action }}"
          echo "PR number: ${{ github.event.pull_request.number }}"